version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
  db:
    image: mongo
    volumes:
      - datadb:/data/db
    ports:
      - "27017:27017"
volumes:
  datadb:
